#!/usr/bin/env python3
"""
Aegis Shield — Production Setup
================================
One-command production deployment of Aegis Shield with feature flags.

Usage:
  python3 setup_shield.py              # Interactive setup
  python3 setup_shield.py --quick      # Quick defaults (no VPN, mesh-llm upstream)
  python3 setup_shield.py --full       # Everything (VPN + mesh-llm + LLM Guard)
  python3 setup_shield.py --status     # Check current deployment status

Feature Flags (in config/shield.yaml):
  vpn.enabled: true/false         — VPN pool routing
  upstream: mesh-llm|z.ai|custom  — LLM provider
  llm_guard.enabled: true/false   — LLM Guard scanners
  monitoring.enabled: true/false  — Traffic monitor + cron
"""

import sys
import json
import subprocess
import time
from pathlib import Path
import yaml  # We'll write this without yaml dep if needed

SHIELD_ROOT = Path.home() / "AegisGate"
VPN_POOL = SHIELD_ROOT / "vpn-pool"
CONFIG_FILE = SHIELD_ROOT / "config" / "shield.yaml"
ENV_FILE = SHIELD_ROOT / "config" / ".env"
DEFAULT_CONFIG = {
    "vpn": {"enabled": False, "provider": "vpngate", "country_preference": "any"},
    "upstream": "mesh-llm",  # mesh-llm | z.ai | custom
    "upstream_urls": {
        "mesh-llm": "http://localhost:9337/v1",
        "z.ai": "https://api.z.ai/api/coding/paas/v4",
        "custom": ""
    },
    "llm_guard": {"enabled": False},
    "monitoring": {"enabled": True, "cron_interval_hours": 4},
    "routing": {"ports_through_vpn": [18080]},
}


def write_yaml(path: Path, data: dict):
    """Write simple YAML without pyyaml dependency."""
    with open(path, "w") as f:
        f.write("# Aegis Shield Configuration\n")
        f.write("# Generated by setup_shield.py\n\n")
        for section, values in data.items():
            if isinstance(values, dict):
                f.write(f"{section}:\n")
                for k, v in values.items():
                    if isinstance(v, dict):
                        f.write(f"  {k}:\n")
                        for sk, sv in v.items():
                            f.write(f"    {sk}: {json.dumps(sv)}\n")
                    elif isinstance(v, list):
                        f.write(f"  {k}: {json.dumps(v)}\n")
                    elif isinstance(v, bool):
                        f.write(f"  {k}: {str(v).lower()}\n")
                    else:
                        f.write(f"  {k}: {v}\n")
            else:
                f.write(f"{section}: {values}\n")


def read_yaml(path: Path) -> dict:
    """Read simple YAML without pyyaml dependency."""
    if not path.exists():
        return {}
    config = {}
    current_section = None
    current_subsection = None
    with open(path) as f:
        for line in f:
            line = line.rstrip()
            if not line or line.startswith("#"):
                continue
            if not line.startswith(" "):
                current_section = line.rstrip(":")
                config[current_section] = {}
                current_subsection = None
            elif line.startswith("    ") and current_section:
                # Sub-sub key
                key, _, val = line.strip().partition(": ")
                if current_subsection and current_subsection in config[current_section]:
                    config[current_section][current_subsection][key] = _parse_val(val)
            elif line.startswith("  ") and current_section:
                key, _, val = line.strip().partition(": ")
                if val.startswith("{") or key == "":  # new subsection
                    current_subsection = key
                    if current_subsection:
                        config[current_section][current_subsection] = {}
                else:
                    config[current_section][key] = _parse_val(val)
    return config


def _parse_val(val: str):
    val = val.strip()
    if val == "true": return True
    if val == "false": return False
    try:
        return json.loads(val)
    except (json.JSONDecodeError, ValueError):
        return val


def check_status():
    """Print full deployment status."""
    config = read_yaml(CONFIG_FILE)
    
    print(f"""
╔══════════════════════════════════════════════════════════╗
║           Aegis Shield — Production Status                ║
╠══════════════════════════════════════════════════════════╣""")
    
    # AegisGate
    try:
        import urllib.request
        req = urllib.request.Request("http://localhost:18080/health")
        with urllib.request.urlopen(req, timeout=3) as resp:
            if resp.status == 200:
                print("║  ● AegisGate  :18080 — HEALTHY                         ║")
            else:
                print("║  ○ AegisGate  :18080 — DOWN                            ║")
    except Exception:
        print("║  ○ AegisGate  :18080 — DOWN                            ║")
    
    # VPN
    try:
        r = subprocess.run(["ip", "link", "show", "tun0"], capture_output=True, text=True, timeout=3)
        if "UP" in r.stdout:
            active = "CONNECTED"
            # Get country
            state_file = VPN_POOL / "pool_state.json"
            country = "?"
            if state_file.exists():
                with open(state_file) as sf:
                    s = json.load(sf)
                    country = s.get("active", {}).get("country_long", s.get("active", {}).get("country", "?"))
            print(f"║  ● VPN        tun0 — {active} ({country})                    ║")
        else:
            print("║  ○ VPN        tun0 — DISCONNECTED                      ║")
    except Exception:
        print("║  ○ VPN        tun0 — DISCONNECTED                      ║")
    
    # mesh-llm
    try:
        import urllib.request
        req = urllib.request.Request("http://localhost:9337/v1/models")
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read())
            n = len(data.get("data", []))
            print(f"║  ● mesh-llm   :9337 — {n} models                         ║")
    except Exception:
        print("║  ○ mesh-llm   :9337 — DOWN                              ║")
    
    # LLM Guard
    try:
        import llm_guard
        print("║  ● LLM Guard  — INSTALLED                               ║")
    except ImportError:
        print("║  ○ LLM Guard  — NOT INSTALLED                           ║")
    
    # Toggle server
    try:
        import urllib.request
        req = urllib.request.Request("http://localhost:9217/vpn-status")
        with urllib.request.urlopen(req, timeout=2) as resp:
            print("║  ● Toggle     :9217 — RUNNING                           ║")
    except Exception:
        print("║  ○ Toggle     :9217 — STOPPED                           ║")
    
    # Config
    if config:
        vpn_enabled = config.get("vpn", {}).get("enabled", False)
        upstream = config.get("upstream", "?")
        llm_enabled = config.get("llm_guard", {}).get("enabled", False)
        print("╠══════════════════════════════════════════════════════════╣")
        print(f"║  Config: vpn={'ON' if vpn_enabled else 'off'} upstream={upstream} llm_guard={'ON' if llm_enabled else 'off'}      ║")
    else:
        print("╠══════════════════════════════════════════════════════════╣")
        print("║  Config: not yet initialized — run setup_shield.py       ║")
    
    print("╚══════════════════════════════════════════════════════════╝")


def setup_quick():
    """Quick setup: mesh-llm upstream, no VPN, basic monitoring."""
    config = DEFAULT_CONFIG.copy()
    config["vpn"]["enabled"] = False
    config["llm_guard"]["enabled"] = False
    write_yaml(CONFIG_FILE, config)
    
    # Set mesh-llm as upstream in .env
    subprocess.run([
        "sed", "-i",
        "s|AEGIS_UPSTREAM_BASE_URL=.*|AEGIS_UPSTREAM_BASE_URL=http://localhost:9337/v1|",
        str(ENV_FILE)
    ])
    
    print("✓ Quick setup complete — mesh-llm upstream, no VPN")


def setup_full():
    """Full setup: VPN + mesh-llm + LLM Guard (if installed)."""
    config = DEFAULT_CONFIG.copy()
    config["vpn"]["enabled"] = True
    
    try:
        import llm_guard
        config["llm_guard"]["enabled"] = True
    except ImportError:
        config["llm_guard"]["enabled"] = False
    
    write_yaml(CONFIG_FILE, config)
    
    # Set mesh-llm as upstream
    subprocess.run([
        "sed", "-i",
        "s|AEGIS_UPSTREAM_BASE_URL=.*|AEGIS_UPSTREAM_BASE_URL=http://localhost:9337/v1|",
        str(ENV_FILE)
    ])
    
    print("✓ Full setup complete")
    if not config["llm_guard"]["enabled"]:
        print("  ⚠ LLM Guard not installed — run: pip install llm-guard")


def main():
    if len(sys.argv) < 2:
        print("Usage: setup_shield.py [--quick|--full|--status]")
        check_status()
        return
    
    cmd = sys.argv[1]
    
    if cmd == "--quick":
        setup_quick()
    elif cmd == "--full":
        setup_full()
    elif cmd == "--status":
        check_status()
    else:
        print(f"Unknown: {cmd}")
        print("Usage: setup_shield.py [--quick|--full|--status]")


if __name__ == "__main__":
    main()
